"""Remove enum in user

Revision ID: 1390075a1b24
Revises: 99e99deec4bb
Create Date: 2023-06-09 18:40:11.959942

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1390075a1b24'
down_revision = '99e99deec4bb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
