"""Change retail to user

Revision ID: 1ae25832d7e6
Revises: c2f550123f4e
Create Date: 2023-06-09 00:00:41.542779

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1ae25832d7e6'
down_revision = 'c2f550123f4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
