"""Add user to institution

Revision ID: 1bc581df1012
Revises: 1390075a1b24
Create Date: 2023-06-09 18:52:49.680275

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc581df1012'
down_revision = '1390075a1b24'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
