"""Change enum to str

Revision ID: 3cd4a9ccd9fe
Revises: c082f28530c2
Create Date: 2023-06-09 23:16:59.175597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cd4a9ccd9fe'
down_revision = 'c082f28530c2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.add_column('users', sa.Column('role', sa.String(length=128), nullable=False, default="User"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
