"""Change role in Institution

Revision ID: 507c87159f17
Revises: 3cd4a9ccd9fe
Create Date: 2023-06-10 03:24:58.061691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '507c87159f17'
down_revision = '3cd4a9ccd9fe'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
