"""Change stuff

Revision ID: 693608e1c99e
Revises: a79858a5867d
Create Date: 2023-06-08 17:10:53.720899

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '693608e1c99e'
down_revision = 'a79858a5867d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('institutions_user_id_fkey', 'institutions', type_='foreignkey')
    op.drop_constraint('projects_developer_id_fkey', 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'institutions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_table('institutionals')
    op.create_foreign_key(None, 'projects', 'institutions', ['developer_id'], ['institution_id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('firstName', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('lastName', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('accreditedInvestor', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('phoneNumber', sa.String(length=128), nullable=True))
    op.add_column('users', sa.Column('country', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'country')
    op.drop_column('users', 'phoneNumber')
    op.drop_column('users', 'accreditedInvestor')
    op.drop_column('users', 'lastName')
    op.drop_column('users', 'firstName')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key('projects_developer_id_fkey', 'projects', 'institutionals', ['developer_id'], ['institutional_id'])
    op.drop_constraint(None, 'institutions', type_='foreignkey')
    op.create_foreign_key('institutions_user_id_fkey', 'institutions', 'users', ['user_id'], ['id'])
    op.create_table('institutionals',
    sa.Column('institutional_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('subrole', postgresql.ENUM('ENERGY_PROJECT_DEVELOPER', 'NATURE_BASED_PROJECT_DEVELOPER', 'FINANCIAL_INSTITUTION', 'ENTERPRISE_AND_NGO', 'OTHER', name='institutionalrole'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('organization_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('country', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organization_address', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('organization_registration_number', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('assets_under_management', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('investment_ticket_preference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('product_preference', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('regions_of_interest', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('sector_of_interest', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='institutionals_user_id_fkey'),
    sa.PrimaryKeyConstraint('institutional_id', name='institutionals_pkey')
    )
    # ### end Alembic commands ###
