"""Change db

Revision ID: 99e99deec4bb
Revises: 1ae25832d7e6
Create Date: 2023-06-09 17:47:53.482716

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e99deec4bb'
down_revision = '1ae25832d7e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
