"""Add history and verified

Revision ID: a162433e04f2
Revises: 507c87159f17
Create Date: 2023-07-05 00:48:24.253996

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a162433e04f2'
down_revision = '507c87159f17'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('histories', sa.Column('time', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('verified', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'verified')
    op.drop_column('histories', 'time')
    # ### end Alembic commands ###
