"""Users revision

Revision ID: a79858a5867d
Revises: 47000cc41edb
Create Date: 2023-05-31 16:51:06.295010

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a79858a5867d'
down_revision = '47000cc41edb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('project')
    op.drop_table('corporates')

    op.add_column('projects', sa.Column('developer_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'projects', 'institutionals', ['developer_id'], ['institutional_id'])
    op.add_column('users', sa.Column('whitelisted', sa.Boolean(), nullable=True))
    op.drop_column('users', 'public_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('public_key', sa.VARCHAR(length=64), autoincrement=False, nullable=True))
    op.drop_column('users', 'whitelisted')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_column('projects', 'developer_id')
    op.create_table('project',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('corporate_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['corporate_id'], ['corporates.id'], name='project_corporate_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='project_pkey')
    )
    op.create_table('corporates',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('corporates_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('subrole', postgresql.ENUM('GOVERNMENT', 'PROJECT_DEVELOPER', 'FINANCE_INSTRUMENT', 'ENTERPRISE', name='corporaterole'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='corporates_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='corporates_pkey')
    )
    # ### end Alembic commands ###
